version: '2'
services:
  postgres:
    restart: always
    image: postgres
    expose:
      - '5432'
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    expose:
      - '6379'
    volumes:
      - ./redis/redisdata:/data

  web:
    restart: always
    build: ./web
    expose:
      - '8000'
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./web/app_code:/app_code
    env_file: ./web/.env
    command: /usr/local/bin/gunicorn generic_store.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx
    ports: 
      - '80:80'
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web


